### ISSUE TITLE
RoT/SP image versioning (including rollback)

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/hubris#1127]

**Comment by lzrd** [comment]
This has been identified as three issues.

This issue:

1) Caboose allows RoT and SP images to carry version information.
The build and release procedures need to add non-default/intentional version strings to the images.
permission_slip should enforce non-default version strings.
The release engineering and procedures should automate/facilitate acceptable versioning. 

Other issues:

2) RoT root key and certificate revocation is a form of rollback protection.
Bootleby and the LPC55 ROM implement secure boot which will respect invalidation of keys.
The process and procedures for configuring those mechanisms are not yet implemented.

3) A software anti-rollback epoch mechanism implemented by `update_server` using an epoch stored in the caboose needs to be implemented. A well-behaved `update_server` would refuse to update and/or enable an image with an epoch numerically lower than its own.

**Comment by andrewjstone** [comment]
I would close this issue and open a separate one for (2) if it doesn't exist. I think (3) can be served by https://github.com/oxidecomputer/hubris/issues/1366 with details added there.
