### ISSUE TITLE
Gimlet sequencer should check for a processor

### ISSUE THREAD

**Issue by rmustacc** [oxidecomputer/hubris#1268]
There are a series of signals that are connected to the SP to indicate whether something is installed in a socket or not. There are three basic checks that are present:

1. Is a CPU installed? This is the `SP3_TO_SP_PRESENT_L` signal aka `CPU_PRESENT_L` on the AMD side.
2. Is this an EPYC or ThreadRipper CPU, aka `SP3_TO_SP_SP3R1` and `SP3_TO_SEQ_SP3R2`. Yes, ignore the SEQ, it goes to the SP.
3. What type of SP3 CPU is this? Basically a way to distinguish between Naples and Rome/Milan. This is `SP3_TO_SP_CORETYPE` covers this.

The SP should check all of these in roughly that order before proceeding to sequence.

**Comment by nathanaelhuffman** [comment]
We should consider the SDLE use case also. It is possible that it straps things appropriately but we need to confirm. We already have to load a special fpga for SDLE since it doesn’t properly mimic sequencing handshakes so we can possibly work around this there and still show hubris that a cpu is installed etc.
