### ISSUE TITLE
Sprot: Protect against DoS if CSn asserted indefinitely by the SP?

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/hubris#1270]
I'm not sure this is something we should try to deal with on the RoT. The control plane should notice if the RoT is unavailable. In order to mitigate, we'd have to put a timeout check in our tight loop reading bytes from SPI which is less than ideal. 

There's also a question of what to do on detection. @lzrd suggested resetting the SP.

I'm opening this issue for discussion, and to get it out of a TODO in the code.

**Comment by cbiffle** [comment]
Currently, I don't think we should take any action on the SP holding CS for weird intervals of time. Since the RoT has no other communication path to the rest of the system other than the SP, if the SP jams the SPI link, there's not a lot the RoT can do.

The RoT only acts asynchronously in the current design if it detects an SP reset. Everything else is in response to a command from the SP. If the SP is jamming the SPI link, no commands from the SP can arrive; if the SP resets, it will release CS, ending the condition.

The control plane might decide to reset the SP in extreme cases of unavailability, which would also fix the CS jamming.

**Comment by andrewjstone** [comment]
@cbiffle I think your analysis is sound. I'm going to close this.
