### ISSUE TITLE
Determine production CMPA base configuration

### ISSUE THREAD

**Issue by kc8apf** [oxidecomputer/hubris#1289]
LPC55S69 CMPA is a mix of security and power-on-reset configuration.  At least some of the security bits (hash of root key table) will vary depending on which signing keys are used and thus need to be filled in by the signing infrastructure.  There are other parts (such as what clock speed to start at) that are more application-dependent and fixed across signing environments.  These latter bits need to be decided on, documented, and possibly generated by the build system.

**Comment by kc8apf** [comment]
Depends on oxidecomputer/lpc55_support#62 and oxidecomputer/humility#371 to determine DCFG_CC_SOCU settings.

**Comment by cbiffle** [comment]
Well, here's an attempt at a conversation starter:

Boot failure pin: as dictated by product schematic.

Boot speed: 96 MHz, not configurable, we have no need for 48MHz default config.

Default ISP Mode: set to UART, mostly to try to avoid USB ISP from activating since it contains known flaws.

USB PID/VID: zero.

Debug authentication / default debug state bits: as outlined in your RFD.

Secure boot: on

Block PUF enrollment: no (allow identity key to potentially be rotated in the future)

Block PUF set key: no

TZM Image type: use type from header.

Skip dice: no (in other words, do DICE)

Dice cust cfg (i.e. include CFPA in DICE CDI): no?

Include NXP config in DICE: yes?

Use RSA4096 keys only: no (allow 2048 keys)?

All PRINCE-related fields: 0.

Reserved usage past 256 bytes: 0.

**Comment by cbiffle** [comment]
The root key hashes, of course, are waiting for the root keys to exist. Otherwise between our well-tested defaults for the fields we don't really depend on and the contents of RFD 333, I think we could specify this today.

**Comment by cbiffle** [comment]
This is still waiting on root key hashes, fwiw.

**Comment by kc8apf** [comment]
> Use RSA4096 keys only: no (allow 2048 keys)?

This particular field gets overridden by `lpc55_sign cmpa` based on the key size used in the root certificates.

**Comment by cbiffle** [comment]
As of this afternoon we've got something plausible.
