### ISSUE TITLE
Gimlet sequencer: Add ringbuf logging for source/cause of A2 transitions

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/hubris#1950]
Today in manufacturing we had a situation where 5 sleds had rebooted from the host's perspective, but the SPs had not reset. We were unable to find any evidence on the host side about what caused the reboots. Particularly curiously, the uptimes on all 5 sleds were almost identical, so it appears all five made A2 -> A0 transitions at roughly the same time.

@rmustacc suggested an easy extension to the sequencer ringbufs that would help in a situation like this: whenever the sequencer gets a request to change the power state, can we require callers to pass in something that describes the source or cause (e.g., request via control plane agent vs request from ipcc vs ...)?

**Comment by hawkw** [comment]
So, we could certainly make all callers of the IPC interface provide some enum identifying themselves or something. Another potential option, though, would be to just have the sequencer server stick the task ID of the caller of `Sequencer.set_state` in the ringbuf. That would be a less intrusive change as it doesn't change the IPC interface, and it also avoids adding another byte to the size of the IPC message (which may not be all that important). But, the ringbuf entries might look a little less nice, as it's just an integer task ID instead of an enum with a name that Humility can interpret...

**Comment by jgallagher** [comment]
I'd vote update the IPC interface. `host-sp-comms`, at least, can ask for power state changes for a few different reasons, and it'd be good to capture those.
