### ISSUE TITLE
UB in userlib::hl::send: pointer passed to from_raw_parts_mut must point to initialized T

### ISSUE THREAD

**Issue by saethlin** [oxidecomputer/hubris#277]
https://github.com/oxidecomputer/hubris/blob/8833cc1dcfdbf107369e188a035a38651ba7ab46/sys/userlib/src/hl.rs#L519-L525

[`slice::from_raw_parts_mut`](https://doc.rust-lang.org/stable/std/slice/fn.from_raw_parts_mut.html) documents that
> data must point to len consecutive properly initialized values of type T.

I see that `M::Response` requires `zerocopy::FromBytes`. I _think_ this trait bound means that the pointed-to data for the slice could be initialized with `core::mem::zeroed()`. But it's totally unclear to me if this initialization imposes too much overhead, and the interface for `sys_send` should be to pass through the `MaybeUninit`-ness of the data by using a `&[MaybeUninit<u8>]` instead of `&[u8]`.

**Comment by cbiffle** [comment]
Nice observation! Messages tend to be relatively small, so `zeroed` is probably affordable -- in fact I think `zerocopy` provides a constructor that does the equivalent for `T: FromBytes`, if I'm not mis-remembering. That said, the suggestion to expose `MaybeUninit` at the syscall boundary _does_ better express the actual behavior here. I'd want to try it and see if it makes code awful. For instance, right now, you can use `sys_send` from safe code -- using `MaybeUninit` here might stop that, since you'd likely need to either transmute on the way in, or `assume_init` on the way out. Hmmmm.
